import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Button from "../components/Button";
import Card from "../components/Card";
import Contact from "../components/Contact";
import Navbar from "../components/Navbar";
import Reviews from "../components/Reviews";
import Tiles from "../components/Tiles";
import styles from "../styles/Home.module.css";

const bedData = [
	{
		room: "Bedroom 1",
		beds: "1 king bed",
		closet: "Walk-in closet",
		bathroom: "Shower + Bath",
		work: "Working station with desk + chair",
	},
	{
		room: "Bedroom 2",
		beds: "2 twin beds",
		closet: "Closet",
		bathroom: "Shower",
		work: "Working station with desk + chair",
	},
];

const livingData = {
	room: "Living Room and Dining Area",
	beds: "Pull-out sofa queen bed",
	tv: "65' TV with cable + Roku",
	wifi: "Low latency wifi",
	table: "Dining table",
	fan: "Ceiling Fan",
};

export default function Home() {
	return (
		<div className=" bg-white text-black">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin={true}
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@300;400;500;700&family=Raleway:wght@300;400;500;600&display=swap"
					rel="stylesheet"
				/>
			</Head>

			<div className="grid grid-cols-1 gap-y-10">
				<div className="h-screen">
					<Navbar />

					<div className="mt-12 px-8 lg:px-40 flex flex-col justify-center">
						<Tiles />

						<div className="font-raleway font-thin text-black text-lg pt-4 tracking-tight">
							No other condominiums on Waikiki offer such resort style living as
							The Watermark with its open air lobby, fantastic swimming pool
							facilities, gorgeous ocean, marina, and mountain views. Recently
							renovated with modern hardwood floors and furniture, this special
							unit offers exceptional comfort and style with a fully equipped
							gourmet kitchen, efficient walk-in closet systems, clean marble
							bathrooms, furnished bedrooms with working spaces, a dining area
							and a living room expanding into a lanai for taking in beautiful
							sunset views all around the year. This immaculate unit overlooks
							the Ala Wai canal flowing next to the building, emptying out into
							the ocean. Relax and enjoy the Hawaiian breeze while enjoying the
							breathtaking views of yachts near the Ala Moana Park, blue ocean
							and city lights from the Ala Moana Center just steps away.
						</div>
					</div>
				</div>

				<div id="details" className="px-8 lg:px-40 pt-10">
					<div className="font-playfair text-3xl font-semibold pb-8">
						Property Details
					</div>

					<div className="grid grid-cols-1 md:grid-cols-2 gap-8 pb-8">
						{bedData.map((room) => {
							return (
								<Card
									room={room.room}
									beds={room.beds}
									closet={room.closet}
									bathroom={room.bathroom}
									work={room.work}
								/>
							);
						})}
					</div>

					<div className="font-raleway w-full flex flex-wrap md:flex-nowrap space-x-0 md:space-x-8 items-end">
						<div className="h-64 w-full rounded-xl bg-slate-100 mb-3 md:mb-0"></div>
						<div className="w-96">
							<div className="font-semibold text-base">{livingData.room}</div>
							<div>{livingData.beds}</div>
							<div>{livingData.work}</div>
							<div>{livingData.closet}</div>
							<div>{livingData.bathroom}</div>
							<div>{livingData.tv}</div>
							<div>{livingData.wifi}</div>
							<div>{livingData.table}</div>
							<div>{livingData.fan}</div>
						</div>
					</div>
				</div>

				<div className="px-8 lg:px-40 font-raleway">
					<div className="font-playfair text-3xl font-semibold pb-8">
						Apartment Amenities
					</div>

					<div className="bg-slate-100 rounded-xl h-96"></div>

					<div className="flex justify-center my-20">
						<div className="max-w-4xl grid grid-cols-2 md:grid-cols-6 place-items-center gap-y-12 gap-32 md:gap-4">
							<div className="h-16 flex flex-col justify-between items-center">
								<img src="/swim.svg" className="h-8 w-8" />
								<div className="text-center">Swimming Pool</div>
							</div>
							<div className="h-16 flex flex-col justify-between items-center">
								<img src="/spa.svg" className="h-8 w-8" />
								<div className="text-center">Spa/Hot Tub</div>
							</div>
							<div className="h-16 flex flex-col justify-between items-center">
								<img src="/gym.svg" className="h-8 w-8" />
								<div className="text-center">Fitness Center</div>
							</div>
							<div className="h-16 flex flex-col justify-between items-center">
								<img src="/sauna.svg" className="h-8 w-8" />
								<div className="text-center">Sauna</div>
							</div>
							<div className="h-16 flex flex-col justify-between items-center">
								<img src="/hammock.svg" className="h-8 w-8" />
								<div className="text-center">Outdoor Lounge</div>
							</div>
							<div className="h-16 flex flex-col justify-between items-center">
								<img src="/grill.svg" className="h-8 w-8" />
								<div className="text-center">Outdoor Grill </div>
							</div>
						</div>
					</div>
				</div>

				<div className="px-8 lg:px-40 h-screen font-raleway">
					<Reviews />
				</div>

				<div className="px-8 lg:px-40">
					<div id="contact" className="font-raleway pb-20">
						<div className="font-semibold text-2xl mb-1">Hosted by Julia</div>
						<div className=" text-md text-slate-600 mb-8">
							<div className="font-sans font-light">+1 (609) 819 - 6858</div>
							<div>julia@realty.com</div>
						</div>

						<Link href="/contact">
							<a className="px-4 py-2 border hover:bg-slate-100 border-slate-900 rounded-xl">
								Contact Host
							</a>
						</Link>
					</div>
				</div>
				<div className="bg-slate-700 flex flex-col space-y-20 justify-between px-8 lg:px-40 text-white py-8">
					<div>
						<div className="font-playfair text-3xl font-semibold">
							The Watermark
						</div>
						<div className="font-raleway mt-1">
							<div>1551 Ala Wai Blvd</div>
							<div>Honolulu, HI 96815</div>
						</div>
					</div>
					<div className="font-raleway flex justify-between w-full">
						<a className="cursor-pointer">julia@realty</a>
						<div>
							<div>Designed by Matthew Kim</div>
							<div className="flex justify-end space-x-2 ">
								<svg
									xmlns="http://www.w3.org/2000/svg"
									viewBox="0 0 24 24"
									fill="currentColor"
									className="w-6 h-6"
								>
									<path
										fillRule="evenodd"
										d="M12 3.75a6.715 6.715 0 00-3.722 1.118.75.75 0 11-.828-1.25 8.25 8.25 0 0112.8 6.883c0 3.014-.574 5.897-1.62 8.543a.75.75 0 01-1.395-.551A21.69 21.69 0 0018.75 10.5 6.75 6.75 0 0012 3.75zM6.157 5.739a.75.75 0 01.21 1.04A6.715 6.715 0 005.25 10.5c0 1.613-.463 3.12-1.265 4.393a.75.75 0 01-1.27-.8A6.715 6.715 0 003.75 10.5c0-1.68.503-3.246 1.367-4.55a.75.75 0 011.04-.211zM12 7.5a3 3 0 00-3 3c0 3.1-1.176 5.927-3.105 8.056a.75.75 0 11-1.112-1.008A10.459 10.459 0 007.5 10.5a4.5 4.5 0 119 0c0 .547-.022 1.09-.067 1.626a.75.75 0 01-1.495-.123c.041-.495.062-.996.062-1.503a3 3 0 00-3-3zm0 2.25a.75.75 0 01.75.75A15.69 15.69 0 018.97 20.738a.75.75 0 01-1.14-.975A14.19 14.19 0 0011.25 10.5a.75.75 0 01.75-.75zm3.239 5.183a.75.75 0 01.515.927 19.415 19.415 0 01-2.585 5.544.75.75 0 11-1.243-.84 17.912 17.912 0 002.386-5.116.75.75 0 01.927-.515z"
										clipRule="evenodd"
									/>
								</svg>
								<div>github: matthewkim</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}
